#!/bin/sh
# Author: Bert Freudenberg
# Purpose: Run etoys using the old Sugar launch procedure which comes
#          pre-installed on the first mass-produced machines (Trial-3/Ship.1)
#          The new Sugar (Joyride/Update.1) uses bin/etoys-activity instead.
#
# This version of etoys-activity is only called under old Sugar.
# The old procedure required a dbus factory service:

exec `dirname $0`/old-drgeo2-factory org.ofset.DrGeoII old-drgeo2-instance

